all: LibraryManagementSystem

LibraryManagementSystem: LibraryManagementSystem.cpp TemplateDoublyLinkedList.h
	g++-4.7 -std=c++11 LibraryManagementSystem.cpp -o LibraryManagementSystem

clean:
	rm *.o *.gch LibraryManagementSystem
